/*
 * This file is generated by jOOQ.
 */
package my.startup.performance_schema.tables;


import javax.annotation.processing.Generated;

import my.startup.performance_schema.PerformanceSchema;
import my.startup.performance_schema.tables.records.SessionAccountConnectAttrsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionAccountConnectAttrs extends TableImpl<SessionAccountConnectAttrsRecord> {

    private static final long serialVersionUID = 203792547;

    /**
     * The reference instance of <code>performance_schema.session_account_connect_attrs</code>
     */
    public static final SessionAccountConnectAttrs SESSION_ACCOUNT_CONNECT_ATTRS = new SessionAccountConnectAttrs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SessionAccountConnectAttrsRecord> getRecordType() {
        return SessionAccountConnectAttrsRecord.class;
    }

    /**
     * Create a <code>performance_schema.session_account_connect_attrs</code> table reference
     */
    public SessionAccountConnectAttrs() {
        this(DSL.name("session_account_connect_attrs"), null);
    }

    /**
     * Create an aliased <code>performance_schema.session_account_connect_attrs</code> table reference
     */
    public SessionAccountConnectAttrs(String alias) {
        this(DSL.name(alias), SESSION_ACCOUNT_CONNECT_ATTRS);
    }

    /**
     * Create an aliased <code>performance_schema.session_account_connect_attrs</code> table reference
     */
    public SessionAccountConnectAttrs(Name alias) {
        this(alias, SESSION_ACCOUNT_CONNECT_ATTRS);
    }

    private SessionAccountConnectAttrs(Name alias, Table<SessionAccountConnectAttrsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SessionAccountConnectAttrs(Name alias, Table<SessionAccountConnectAttrsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SessionAccountConnectAttrs(Table<O> child, ForeignKey<O, SessionAccountConnectAttrsRecord> key) {
        super(child, key, SESSION_ACCOUNT_CONNECT_ATTRS);
    }

    @Override
    public Schema getSchema() {
        return PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    @Override
    public SessionAccountConnectAttrs as(String alias) {
        return new SessionAccountConnectAttrs(DSL.name(alias), this);
    }

    @Override
    public SessionAccountConnectAttrs as(Name alias) {
        return new SessionAccountConnectAttrs(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SessionAccountConnectAttrs rename(String name) {
        return new SessionAccountConnectAttrs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SessionAccountConnectAttrs rename(Name name) {
        return new SessionAccountConnectAttrs(name, null);
    }
}
