/*
 * This file is generated by jOOQ.
 */
package my.startup.performance_schema.tables.records;


import javax.annotation.processing.Generated;

import my.startup.performance_schema.tables.GlobalStatus;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GlobalStatusRecord extends TableRecordImpl<GlobalStatusRecord> {

    private static final long serialVersionUID = -421978111;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GlobalStatusRecord
     */
    public GlobalStatusRecord() {
        super(GlobalStatus.GLOBAL_STATUS);
    }
}
