/*
 * This file is generated by jOOQ.
 */
package my.startup.performance_schema.tables.records;


import javax.annotation.processing.Generated;

import my.startup.performance_schema.tables.SessionStatus;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionStatusRecord extends TableRecordImpl<SessionStatusRecord> {

    private static final long serialVersionUID = 416822776;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionStatusRecord
     */
    public SessionStatusRecord() {
        super(SessionStatus.SESSION_STATUS);
    }
}
