/*
 * This file is generated by jOOQ.
 */
package my.startup.performance_schema.tables.records;


import javax.annotation.processing.Generated;

import my.startup.performance_schema.tables.SessionAccountConnectAttrs;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionAccountConnectAttrsRecord extends TableRecordImpl<SessionAccountConnectAttrsRecord> {

    private static final long serialVersionUID = -930201795;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionAccountConnectAttrsRecord
     */
    public SessionAccountConnectAttrsRecord() {
        super(SessionAccountConnectAttrs.SESSION_ACCOUNT_CONNECT_ATTRS);
    }
}
