/*
 * This file is generated by jOOQ.
 */
package my.startup.performance_schema.tables.records;


import javax.annotation.processing.Generated;

import my.startup.performance_schema.tables.VariablesInfo;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VariablesInfoRecord extends TableRecordImpl<VariablesInfoRecord> {

    private static final long serialVersionUID = -609852573;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VariablesInfoRecord
     */
    public VariablesInfoRecord() {
        super(VariablesInfo.VARIABLES_INFO);
    }
}
