/*
 * This file is generated by jOOQ.
 */
package my.startup.information_schema;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import my.startup.DefaultCatalog;
import my.startup.information_schema.tables.AdministrableRoleAuthorizations;
import my.startup.information_schema.tables.ApplicableRoles;
import my.startup.information_schema.tables.CharacterSets;
import my.startup.information_schema.tables.CheckConstraints;
import my.startup.information_schema.tables.CollationCharacterSetApplicability;
import my.startup.information_schema.tables.Collations;
import my.startup.information_schema.tables.ColumnPrivileges;
import my.startup.information_schema.tables.ColumnStatistics;
import my.startup.information_schema.tables.Columns;
import my.startup.information_schema.tables.ColumnsExtensions;
import my.startup.information_schema.tables.EnabledRoles;
import my.startup.information_schema.tables.Engines;
import my.startup.information_schema.tables.Events;
import my.startup.information_schema.tables.Files;
import my.startup.information_schema.tables.InnodbBufferPage;
import my.startup.information_schema.tables.InnodbBufferPageLru;
import my.startup.information_schema.tables.InnodbBufferPoolStats;
import my.startup.information_schema.tables.InnodbCachedIndexes;
import my.startup.information_schema.tables.InnodbCmp;
import my.startup.information_schema.tables.InnodbCmpPerIndex;
import my.startup.information_schema.tables.InnodbCmpPerIndexReset;
import my.startup.information_schema.tables.InnodbCmpReset;
import my.startup.information_schema.tables.InnodbCmpmem;
import my.startup.information_schema.tables.InnodbCmpmemReset;
import my.startup.information_schema.tables.InnodbColumns;
import my.startup.information_schema.tables.InnodbDatafiles;
import my.startup.information_schema.tables.InnodbFields;
import my.startup.information_schema.tables.InnodbForeign;
import my.startup.information_schema.tables.InnodbForeignCols;
import my.startup.information_schema.tables.InnodbFtBeingDeleted;
import my.startup.information_schema.tables.InnodbFtConfig;
import my.startup.information_schema.tables.InnodbFtDefaultStopword;
import my.startup.information_schema.tables.InnodbFtDeleted;
import my.startup.information_schema.tables.InnodbFtIndexCache;
import my.startup.information_schema.tables.InnodbFtIndexTable;
import my.startup.information_schema.tables.InnodbIndexes;
import my.startup.information_schema.tables.InnodbMetrics;
import my.startup.information_schema.tables.InnodbSessionTempTablespaces;
import my.startup.information_schema.tables.InnodbTables;
import my.startup.information_schema.tables.InnodbTablespaces;
import my.startup.information_schema.tables.InnodbTablespacesBrief;
import my.startup.information_schema.tables.InnodbTablestats;
import my.startup.information_schema.tables.InnodbTempTableInfo;
import my.startup.information_schema.tables.InnodbTrx;
import my.startup.information_schema.tables.InnodbVirtual;
import my.startup.information_schema.tables.KeyColumnUsage;
import my.startup.information_schema.tables.Keywords;
import my.startup.information_schema.tables.OptimizerTrace;
import my.startup.information_schema.tables.Parameters;
import my.startup.information_schema.tables.Partitions;
import my.startup.information_schema.tables.Plugins;
import my.startup.information_schema.tables.Processlist;
import my.startup.information_schema.tables.Profiling;
import my.startup.information_schema.tables.ReferentialConstraints;
import my.startup.information_schema.tables.ResourceGroups;
import my.startup.information_schema.tables.RoleColumnGrants;
import my.startup.information_schema.tables.RoleRoutineGrants;
import my.startup.information_schema.tables.RoleTableGrants;
import my.startup.information_schema.tables.Routines;
import my.startup.information_schema.tables.SchemaPrivileges;
import my.startup.information_schema.tables.Schemata;
import my.startup.information_schema.tables.SchemataExtensions;
import my.startup.information_schema.tables.StGeometryColumns;
import my.startup.information_schema.tables.StSpatialReferenceSystems;
import my.startup.information_schema.tables.StUnitsOfMeasure;
import my.startup.information_schema.tables.Statistics;
import my.startup.information_schema.tables.TableConstraints;
import my.startup.information_schema.tables.TableConstraintsExtensions;
import my.startup.information_schema.tables.TablePrivileges;
import my.startup.information_schema.tables.Tables;
import my.startup.information_schema.tables.TablesExtensions;
import my.startup.information_schema.tables.Tablespaces;
import my.startup.information_schema.tables.TablespacesExtensions;
import my.startup.information_schema.tables.Triggers;
import my.startup.information_schema.tables.UserAttributes;
import my.startup.information_schema.tables.UserPrivileges;
import my.startup.information_schema.tables.ViewRoutineUsage;
import my.startup.information_schema.tables.ViewTableUsage;
import my.startup.information_schema.tables.Views;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationSchema extends SchemaImpl {

    private static final long serialVersionUID = 1435703246;

    /**
     * The reference instance of <code>information_schema</code>
     */
    public static final InformationSchema INFORMATION_SCHEMA = new InformationSchema();

    /**
     * The table <code>information_schema.ADMINISTRABLE_ROLE_AUTHORIZATIONS</code>.
     */
    public final AdministrableRoleAuthorizations ADMINISTRABLE_ROLE_AUTHORIZATIONS = my.startup.information_schema.tables.AdministrableRoleAuthorizations.ADMINISTRABLE_ROLE_AUTHORIZATIONS;

    /**
     * The table <code>information_schema.APPLICABLE_ROLES</code>.
     */
    public final ApplicableRoles APPLICABLE_ROLES = my.startup.information_schema.tables.ApplicableRoles.APPLICABLE_ROLES;

    /**
     * The table <code>information_schema.CHARACTER_SETS</code>.
     */
    public final CharacterSets CHARACTER_SETS = my.startup.information_schema.tables.CharacterSets.CHARACTER_SETS;

    /**
     * The table <code>information_schema.CHECK_CONSTRAINTS</code>.
     */
    public final CheckConstraints CHECK_CONSTRAINTS = my.startup.information_schema.tables.CheckConstraints.CHECK_CONSTRAINTS;

    /**
     * The table <code>information_schema.COLLATIONS</code>.
     */
    public final Collations COLLATIONS = my.startup.information_schema.tables.Collations.COLLATIONS;

    /**
     * The table <code>information_schema.COLLATION_CHARACTER_SET_APPLICABILITY</code>.
     */
    public final CollationCharacterSetApplicability COLLATION_CHARACTER_SET_APPLICABILITY = my.startup.information_schema.tables.CollationCharacterSetApplicability.COLLATION_CHARACTER_SET_APPLICABILITY;

    /**
     * The table <code>information_schema.COLUMNS</code>.
     */
    public final Columns COLUMNS = my.startup.information_schema.tables.Columns.COLUMNS;

    /**
     * The table <code>information_schema.COLUMNS_EXTENSIONS</code>.
     */
    public final ColumnsExtensions COLUMNS_EXTENSIONS = my.startup.information_schema.tables.ColumnsExtensions.COLUMNS_EXTENSIONS;

    /**
     * The table <code>information_schema.COLUMN_PRIVILEGES</code>.
     */
    public final ColumnPrivileges COLUMN_PRIVILEGES = my.startup.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

    /**
     * The table <code>information_schema.COLUMN_STATISTICS</code>.
     */
    public final ColumnStatistics COLUMN_STATISTICS = my.startup.information_schema.tables.ColumnStatistics.COLUMN_STATISTICS;

    /**
     * The table <code>information_schema.ENABLED_ROLES</code>.
     */
    public final EnabledRoles ENABLED_ROLES = my.startup.information_schema.tables.EnabledRoles.ENABLED_ROLES;

    /**
     * The table <code>information_schema.ENGINES</code>.
     */
    public final Engines ENGINES = my.startup.information_schema.tables.Engines.ENGINES;

    /**
     * The table <code>information_schema.EVENTS</code>.
     */
    public final Events EVENTS = my.startup.information_schema.tables.Events.EVENTS;

    /**
     * The table <code>information_schema.FILES</code>.
     */
    public final Files FILES = my.startup.information_schema.tables.Files.FILES;

    /**
     * The table <code>information_schema.INNODB_BUFFER_PAGE</code>.
     */
    public final InnodbBufferPage INNODB_BUFFER_PAGE = my.startup.information_schema.tables.InnodbBufferPage.INNODB_BUFFER_PAGE;

    /**
     * The table <code>information_schema.INNODB_BUFFER_PAGE_LRU</code>.
     */
    public final InnodbBufferPageLru INNODB_BUFFER_PAGE_LRU = my.startup.information_schema.tables.InnodbBufferPageLru.INNODB_BUFFER_PAGE_LRU;

    /**
     * The table <code>information_schema.INNODB_BUFFER_POOL_STATS</code>.
     */
    public final InnodbBufferPoolStats INNODB_BUFFER_POOL_STATS = my.startup.information_schema.tables.InnodbBufferPoolStats.INNODB_BUFFER_POOL_STATS;

    /**
     * The table <code>information_schema.INNODB_CACHED_INDEXES</code>.
     */
    public final InnodbCachedIndexes INNODB_CACHED_INDEXES = my.startup.information_schema.tables.InnodbCachedIndexes.INNODB_CACHED_INDEXES;

    /**
     * The table <code>information_schema.INNODB_CMP</code>.
     */
    public final InnodbCmp INNODB_CMP = my.startup.information_schema.tables.InnodbCmp.INNODB_CMP;

    /**
     * The table <code>information_schema.INNODB_CMPMEM</code>.
     */
    public final InnodbCmpmem INNODB_CMPMEM = my.startup.information_schema.tables.InnodbCmpmem.INNODB_CMPMEM;

    /**
     * The table <code>information_schema.INNODB_CMPMEM_RESET</code>.
     */
    public final InnodbCmpmemReset INNODB_CMPMEM_RESET = my.startup.information_schema.tables.InnodbCmpmemReset.INNODB_CMPMEM_RESET;

    /**
     * The table <code>information_schema.INNODB_CMP_PER_INDEX</code>.
     */
    public final InnodbCmpPerIndex INNODB_CMP_PER_INDEX = my.startup.information_schema.tables.InnodbCmpPerIndex.INNODB_CMP_PER_INDEX;

    /**
     * The table <code>information_schema.INNODB_CMP_PER_INDEX_RESET</code>.
     */
    public final InnodbCmpPerIndexReset INNODB_CMP_PER_INDEX_RESET = my.startup.information_schema.tables.InnodbCmpPerIndexReset.INNODB_CMP_PER_INDEX_RESET;

    /**
     * The table <code>information_schema.INNODB_CMP_RESET</code>.
     */
    public final InnodbCmpReset INNODB_CMP_RESET = my.startup.information_schema.tables.InnodbCmpReset.INNODB_CMP_RESET;

    /**
     * The table <code>information_schema.INNODB_COLUMNS</code>.
     */
    public final InnodbColumns INNODB_COLUMNS = my.startup.information_schema.tables.InnodbColumns.INNODB_COLUMNS;

    /**
     * The table <code>information_schema.INNODB_DATAFILES</code>.
     */
    public final InnodbDatafiles INNODB_DATAFILES = my.startup.information_schema.tables.InnodbDatafiles.INNODB_DATAFILES;

    /**
     * The table <code>information_schema.INNODB_FIELDS</code>.
     */
    public final InnodbFields INNODB_FIELDS = my.startup.information_schema.tables.InnodbFields.INNODB_FIELDS;

    /**
     * The table <code>information_schema.INNODB_FOREIGN</code>.
     */
    public final InnodbForeign INNODB_FOREIGN = my.startup.information_schema.tables.InnodbForeign.INNODB_FOREIGN;

    /**
     * The table <code>information_schema.INNODB_FOREIGN_COLS</code>.
     */
    public final InnodbForeignCols INNODB_FOREIGN_COLS = my.startup.information_schema.tables.InnodbForeignCols.INNODB_FOREIGN_COLS;

    /**
     * The table <code>information_schema.INNODB_FT_BEING_DELETED</code>.
     */
    public final InnodbFtBeingDeleted INNODB_FT_BEING_DELETED = my.startup.information_schema.tables.InnodbFtBeingDeleted.INNODB_FT_BEING_DELETED;

    /**
     * The table <code>information_schema.INNODB_FT_CONFIG</code>.
     */
    public final InnodbFtConfig INNODB_FT_CONFIG = my.startup.information_schema.tables.InnodbFtConfig.INNODB_FT_CONFIG;

    /**
     * The table <code>information_schema.INNODB_FT_DEFAULT_STOPWORD</code>.
     */
    public final InnodbFtDefaultStopword INNODB_FT_DEFAULT_STOPWORD = my.startup.information_schema.tables.InnodbFtDefaultStopword.INNODB_FT_DEFAULT_STOPWORD;

    /**
     * The table <code>information_schema.INNODB_FT_DELETED</code>.
     */
    public final InnodbFtDeleted INNODB_FT_DELETED = my.startup.information_schema.tables.InnodbFtDeleted.INNODB_FT_DELETED;

    /**
     * The table <code>information_schema.INNODB_FT_INDEX_CACHE</code>.
     */
    public final InnodbFtIndexCache INNODB_FT_INDEX_CACHE = my.startup.information_schema.tables.InnodbFtIndexCache.INNODB_FT_INDEX_CACHE;

    /**
     * The table <code>information_schema.INNODB_FT_INDEX_TABLE</code>.
     */
    public final InnodbFtIndexTable INNODB_FT_INDEX_TABLE = my.startup.information_schema.tables.InnodbFtIndexTable.INNODB_FT_INDEX_TABLE;

    /**
     * The table <code>information_schema.INNODB_INDEXES</code>.
     */
    public final InnodbIndexes INNODB_INDEXES = my.startup.information_schema.tables.InnodbIndexes.INNODB_INDEXES;

    /**
     * The table <code>information_schema.INNODB_METRICS</code>.
     */
    public final InnodbMetrics INNODB_METRICS = my.startup.information_schema.tables.InnodbMetrics.INNODB_METRICS;

    /**
     * The table <code>information_schema.INNODB_SESSION_TEMP_TABLESPACES</code>.
     */
    public final InnodbSessionTempTablespaces INNODB_SESSION_TEMP_TABLESPACES = my.startup.information_schema.tables.InnodbSessionTempTablespaces.INNODB_SESSION_TEMP_TABLESPACES;

    /**
     * The table <code>information_schema.INNODB_TABLES</code>.
     */
    public final InnodbTables INNODB_TABLES = my.startup.information_schema.tables.InnodbTables.INNODB_TABLES;

    /**
     * The table <code>information_schema.INNODB_TABLESPACES</code>.
     */
    public final InnodbTablespaces INNODB_TABLESPACES = my.startup.information_schema.tables.InnodbTablespaces.INNODB_TABLESPACES;

    /**
     * The table <code>information_schema.INNODB_TABLESPACES_BRIEF</code>.
     */
    public final InnodbTablespacesBrief INNODB_TABLESPACES_BRIEF = my.startup.information_schema.tables.InnodbTablespacesBrief.INNODB_TABLESPACES_BRIEF;

    /**
     * The table <code>information_schema.INNODB_TABLESTATS</code>.
     */
    public final InnodbTablestats INNODB_TABLESTATS = my.startup.information_schema.tables.InnodbTablestats.INNODB_TABLESTATS;

    /**
     * The table <code>information_schema.INNODB_TEMP_TABLE_INFO</code>.
     */
    public final InnodbTempTableInfo INNODB_TEMP_TABLE_INFO = my.startup.information_schema.tables.InnodbTempTableInfo.INNODB_TEMP_TABLE_INFO;

    /**
     * The table <code>information_schema.INNODB_TRX</code>.
     */
    public final InnodbTrx INNODB_TRX = my.startup.information_schema.tables.InnodbTrx.INNODB_TRX;

    /**
     * The table <code>information_schema.INNODB_VIRTUAL</code>.
     */
    public final InnodbVirtual INNODB_VIRTUAL = my.startup.information_schema.tables.InnodbVirtual.INNODB_VIRTUAL;

    /**
     * The table <code>information_schema.KEYWORDS</code>.
     */
    public final Keywords KEYWORDS = my.startup.information_schema.tables.Keywords.KEYWORDS;

    /**
     * The table <code>information_schema.KEY_COLUMN_USAGE</code>.
     */
    public final KeyColumnUsage KEY_COLUMN_USAGE = my.startup.information_schema.tables.KeyColumnUsage.KEY_COLUMN_USAGE;

    /**
     * The table <code>information_schema.OPTIMIZER_TRACE</code>.
     */
    public final OptimizerTrace OPTIMIZER_TRACE = my.startup.information_schema.tables.OptimizerTrace.OPTIMIZER_TRACE;

    /**
     * The table <code>information_schema.PARAMETERS</code>.
     */
    public final Parameters PARAMETERS = my.startup.information_schema.tables.Parameters.PARAMETERS;

    /**
     * The table <code>information_schema.PARTITIONS</code>.
     */
    public final Partitions PARTITIONS = my.startup.information_schema.tables.Partitions.PARTITIONS;

    /**
     * The table <code>information_schema.PLUGINS</code>.
     */
    public final Plugins PLUGINS = my.startup.information_schema.tables.Plugins.PLUGINS;

    /**
     * The table <code>information_schema.PROCESSLIST</code>.
     */
    public final Processlist PROCESSLIST = my.startup.information_schema.tables.Processlist.PROCESSLIST;

    /**
     * The table <code>information_schema.PROFILING</code>.
     */
    public final Profiling PROFILING = my.startup.information_schema.tables.Profiling.PROFILING;

    /**
     * The table <code>information_schema.REFERENTIAL_CONSTRAINTS</code>.
     */
    public final ReferentialConstraints REFERENTIAL_CONSTRAINTS = my.startup.information_schema.tables.ReferentialConstraints.REFERENTIAL_CONSTRAINTS;

    /**
     * The table <code>information_schema.RESOURCE_GROUPS</code>.
     */
    public final ResourceGroups RESOURCE_GROUPS = my.startup.information_schema.tables.ResourceGroups.RESOURCE_GROUPS;

    /**
     * The table <code>information_schema.ROLE_COLUMN_GRANTS</code>.
     */
    public final RoleColumnGrants ROLE_COLUMN_GRANTS = my.startup.information_schema.tables.RoleColumnGrants.ROLE_COLUMN_GRANTS;

    /**
     * The table <code>information_schema.ROLE_ROUTINE_GRANTS</code>.
     */
    public final RoleRoutineGrants ROLE_ROUTINE_GRANTS = my.startup.information_schema.tables.RoleRoutineGrants.ROLE_ROUTINE_GRANTS;

    /**
     * The table <code>information_schema.ROLE_TABLE_GRANTS</code>.
     */
    public final RoleTableGrants ROLE_TABLE_GRANTS = my.startup.information_schema.tables.RoleTableGrants.ROLE_TABLE_GRANTS;

    /**
     * The table <code>information_schema.ROUTINES</code>.
     */
    public final Routines ROUTINES = my.startup.information_schema.tables.Routines.ROUTINES;

    /**
     * The table <code>information_schema.SCHEMATA</code>.
     */
    public final Schemata SCHEMATA = my.startup.information_schema.tables.Schemata.SCHEMATA;

    /**
     * The table <code>information_schema.SCHEMATA_EXTENSIONS</code>.
     */
    public final SchemataExtensions SCHEMATA_EXTENSIONS = my.startup.information_schema.tables.SchemataExtensions.SCHEMATA_EXTENSIONS;

    /**
     * The table <code>information_schema.SCHEMA_PRIVILEGES</code>.
     */
    public final SchemaPrivileges SCHEMA_PRIVILEGES = my.startup.information_schema.tables.SchemaPrivileges.SCHEMA_PRIVILEGES;

    /**
     * The table <code>information_schema.STATISTICS</code>.
     */
    public final Statistics STATISTICS = my.startup.information_schema.tables.Statistics.STATISTICS;

    /**
     * The table <code>information_schema.ST_GEOMETRY_COLUMNS</code>.
     */
    public final StGeometryColumns ST_GEOMETRY_COLUMNS = my.startup.information_schema.tables.StGeometryColumns.ST_GEOMETRY_COLUMNS;

    /**
     * The table <code>information_schema.ST_SPATIAL_REFERENCE_SYSTEMS</code>.
     */
    public final StSpatialReferenceSystems ST_SPATIAL_REFERENCE_SYSTEMS = my.startup.information_schema.tables.StSpatialReferenceSystems.ST_SPATIAL_REFERENCE_SYSTEMS;

    /**
     * The table <code>information_schema.ST_UNITS_OF_MEASURE</code>.
     */
    public final StUnitsOfMeasure ST_UNITS_OF_MEASURE = my.startup.information_schema.tables.StUnitsOfMeasure.ST_UNITS_OF_MEASURE;

    /**
     * The table <code>information_schema.TABLES</code>.
     */
    public final Tables TABLES = my.startup.information_schema.tables.Tables.TABLES;

    /**
     * The table <code>information_schema.TABLESPACES</code>.
     */
    public final Tablespaces TABLESPACES = my.startup.information_schema.tables.Tablespaces.TABLESPACES;

    /**
     * The table <code>information_schema.TABLESPACES_EXTENSIONS</code>.
     */
    public final TablespacesExtensions TABLESPACES_EXTENSIONS = my.startup.information_schema.tables.TablespacesExtensions.TABLESPACES_EXTENSIONS;

    /**
     * The table <code>information_schema.TABLES_EXTENSIONS</code>.
     */
    public final TablesExtensions TABLES_EXTENSIONS = my.startup.information_schema.tables.TablesExtensions.TABLES_EXTENSIONS;

    /**
     * The table <code>information_schema.TABLE_CONSTRAINTS</code>.
     */
    public final TableConstraints TABLE_CONSTRAINTS = my.startup.information_schema.tables.TableConstraints.TABLE_CONSTRAINTS;

    /**
     * The table <code>information_schema.TABLE_CONSTRAINTS_EXTENSIONS</code>.
     */
    public final TableConstraintsExtensions TABLE_CONSTRAINTS_EXTENSIONS = my.startup.information_schema.tables.TableConstraintsExtensions.TABLE_CONSTRAINTS_EXTENSIONS;

    /**
     * The table <code>information_schema.TABLE_PRIVILEGES</code>.
     */
    public final TablePrivileges TABLE_PRIVILEGES = my.startup.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

    /**
     * The table <code>information_schema.TRIGGERS</code>.
     */
    public final Triggers TRIGGERS = my.startup.information_schema.tables.Triggers.TRIGGERS;

    /**
     * The table <code>information_schema.USER_ATTRIBUTES</code>.
     */
    public final UserAttributes USER_ATTRIBUTES = my.startup.information_schema.tables.UserAttributes.USER_ATTRIBUTES;

    /**
     * The table <code>information_schema.USER_PRIVILEGES</code>.
     */
    public final UserPrivileges USER_PRIVILEGES = my.startup.information_schema.tables.UserPrivileges.USER_PRIVILEGES;

    /**
     * The table <code>information_schema.VIEWS</code>.
     */
    public final Views VIEWS = my.startup.information_schema.tables.Views.VIEWS;

    /**
     * The table <code>information_schema.VIEW_ROUTINE_USAGE</code>.
     */
    public final ViewRoutineUsage VIEW_ROUTINE_USAGE = my.startup.information_schema.tables.ViewRoutineUsage.VIEW_ROUTINE_USAGE;

    /**
     * The table <code>information_schema.VIEW_TABLE_USAGE</code>.
     */
    public final ViewTableUsage VIEW_TABLE_USAGE = my.startup.information_schema.tables.ViewTableUsage.VIEW_TABLE_USAGE;

    /**
     * No further instances allowed
     */
    private InformationSchema() {
        super("information_schema", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AdministrableRoleAuthorizations.ADMINISTRABLE_ROLE_AUTHORIZATIONS,
            ApplicableRoles.APPLICABLE_ROLES,
            CharacterSets.CHARACTER_SETS,
            CheckConstraints.CHECK_CONSTRAINTS,
            Collations.COLLATIONS,
            CollationCharacterSetApplicability.COLLATION_CHARACTER_SET_APPLICABILITY,
            Columns.COLUMNS,
            ColumnsExtensions.COLUMNS_EXTENSIONS,
            ColumnPrivileges.COLUMN_PRIVILEGES,
            ColumnStatistics.COLUMN_STATISTICS,
            EnabledRoles.ENABLED_ROLES,
            Engines.ENGINES,
            Events.EVENTS,
            Files.FILES,
            InnodbBufferPage.INNODB_BUFFER_PAGE,
            InnodbBufferPageLru.INNODB_BUFFER_PAGE_LRU,
            InnodbBufferPoolStats.INNODB_BUFFER_POOL_STATS,
            InnodbCachedIndexes.INNODB_CACHED_INDEXES,
            InnodbCmp.INNODB_CMP,
            InnodbCmpmem.INNODB_CMPMEM,
            InnodbCmpmemReset.INNODB_CMPMEM_RESET,
            InnodbCmpPerIndex.INNODB_CMP_PER_INDEX,
            InnodbCmpPerIndexReset.INNODB_CMP_PER_INDEX_RESET,
            InnodbCmpReset.INNODB_CMP_RESET,
            InnodbColumns.INNODB_COLUMNS,
            InnodbDatafiles.INNODB_DATAFILES,
            InnodbFields.INNODB_FIELDS,
            InnodbForeign.INNODB_FOREIGN,
            InnodbForeignCols.INNODB_FOREIGN_COLS,
            InnodbFtBeingDeleted.INNODB_FT_BEING_DELETED,
            InnodbFtConfig.INNODB_FT_CONFIG,
            InnodbFtDefaultStopword.INNODB_FT_DEFAULT_STOPWORD,
            InnodbFtDeleted.INNODB_FT_DELETED,
            InnodbFtIndexCache.INNODB_FT_INDEX_CACHE,
            InnodbFtIndexTable.INNODB_FT_INDEX_TABLE,
            InnodbIndexes.INNODB_INDEXES,
            InnodbMetrics.INNODB_METRICS,
            InnodbSessionTempTablespaces.INNODB_SESSION_TEMP_TABLESPACES,
            InnodbTables.INNODB_TABLES,
            InnodbTablespaces.INNODB_TABLESPACES,
            InnodbTablespacesBrief.INNODB_TABLESPACES_BRIEF,
            InnodbTablestats.INNODB_TABLESTATS,
            InnodbTempTableInfo.INNODB_TEMP_TABLE_INFO,
            InnodbTrx.INNODB_TRX,
            InnodbVirtual.INNODB_VIRTUAL,
            Keywords.KEYWORDS,
            KeyColumnUsage.KEY_COLUMN_USAGE,
            OptimizerTrace.OPTIMIZER_TRACE,
            Parameters.PARAMETERS,
            Partitions.PARTITIONS,
            Plugins.PLUGINS,
            Processlist.PROCESSLIST,
            Profiling.PROFILING,
            ReferentialConstraints.REFERENTIAL_CONSTRAINTS,
            ResourceGroups.RESOURCE_GROUPS,
            RoleColumnGrants.ROLE_COLUMN_GRANTS,
            RoleRoutineGrants.ROLE_ROUTINE_GRANTS,
            RoleTableGrants.ROLE_TABLE_GRANTS,
            Routines.ROUTINES,
            Schemata.SCHEMATA,
            SchemataExtensions.SCHEMATA_EXTENSIONS,
            SchemaPrivileges.SCHEMA_PRIVILEGES,
            Statistics.STATISTICS,
            StGeometryColumns.ST_GEOMETRY_COLUMNS,
            StSpatialReferenceSystems.ST_SPATIAL_REFERENCE_SYSTEMS,
            StUnitsOfMeasure.ST_UNITS_OF_MEASURE,
            Tables.TABLES,
            Tablespaces.TABLESPACES,
            TablespacesExtensions.TABLESPACES_EXTENSIONS,
            TablesExtensions.TABLES_EXTENSIONS,
            TableConstraints.TABLE_CONSTRAINTS,
            TableConstraintsExtensions.TABLE_CONSTRAINTS_EXTENSIONS,
            TablePrivileges.TABLE_PRIVILEGES,
            Triggers.TRIGGERS,
            UserAttributes.USER_ATTRIBUTES,
            UserPrivileges.USER_PRIVILEGES,
            Views.VIEWS,
            ViewRoutineUsage.VIEW_ROUTINE_USAGE,
            ViewTableUsage.VIEW_TABLE_USAGE);
    }
}
