/*
 * This file is generated by jOOQ.
 */
package org.example.db.jooq.pojo;


import org.example.db.jooq.pojo.tables.Contacts;

/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.article</code>.
     */
    public static final Contacts CONTACTS = Contacts.CONTACTS;

}
