/*
 * This file is generated by jOOQ.
 */
package my.startup.app.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import my.startup.app.App;
import my.startup.app.Indexes;
import my.startup.app.Keys;
import my.startup.app.tables.records.ContactsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contacts extends TableImpl<ContactsRecord> {

    private static final long serialVersionUID = -1012802679;

    /**
     * The reference instance of <code>app.Contacts</code>
     */
    public static final Contacts CONTACTS = new Contacts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContactsRecord> getRecordType() {
        return ContactsRecord.class;
    }

    /**
     * The column <code>app.Contacts.id</code>.
     */
    public final TableField<ContactsRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>app.Contacts.name</code>.
     */
    public final TableField<ContactsRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>app.Contacts.surname</code>.
     */
    public final TableField<ContactsRecord, String> SURNAME = createField(DSL.name("surname"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>app.Contacts</code> table reference
     */
    public Contacts() {
        this(DSL.name("Contacts"), null);
    }

    /**
     * Create an aliased <code>app.Contacts</code> table reference
     */
    public Contacts(String alias) {
        this(DSL.name(alias), CONTACTS);
    }

    /**
     * Create an aliased <code>app.Contacts</code> table reference
     */
    public Contacts(Name alias) {
        this(alias, CONTACTS);
    }

    private Contacts(Name alias, Table<ContactsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Contacts(Name alias, Table<ContactsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Contacts(Table<O> child, ForeignKey<O, ContactsRecord> key) {
        super(child, key, CONTACTS);
    }

    @Override
    public Schema getSchema() {
        return App.APP;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONTACTS_PRIMARY);
    }

    @Override
    public Identity<ContactsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CONTACTS;
    }

    @Override
    public UniqueKey<ContactsRecord> getPrimaryKey() {
        return Keys.KEY_CONTACTS_PRIMARY;
    }

    @Override
    public List<UniqueKey<ContactsRecord>> getKeys() {
        return Arrays.<UniqueKey<ContactsRecord>>asList(Keys.KEY_CONTACTS_PRIMARY);
    }

    @Override
    public Contacts as(String alias) {
        return new Contacts(DSL.name(alias), this);
    }

    @Override
    public Contacts as(Name alias) {
        return new Contacts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Contacts rename(String name) {
        return new Contacts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Contacts rename(Name name) {
        return new Contacts(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
