/*
 * This file is generated by jOOQ.
 */
package my.startup.performance_schema;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import my.startup.DefaultCatalog;
import my.startup.performance_schema.tables.GlobalStatus;
import my.startup.performance_schema.tables.GlobalVariables;
import my.startup.performance_schema.tables.PersistedVariables;
import my.startup.performance_schema.tables.Processlist;
import my.startup.performance_schema.tables.SessionAccountConnectAttrs;
import my.startup.performance_schema.tables.SessionStatus;
import my.startup.performance_schema.tables.SessionVariables;
import my.startup.performance_schema.tables.VariablesInfo;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PerformanceSchema extends SchemaImpl {

    private static final long serialVersionUID = 2027204807;

    /**
     * The reference instance of <code>performance_schema</code>
     */
    public static final PerformanceSchema PERFORMANCE_SCHEMA = new PerformanceSchema();

    /**
     * The table <code>performance_schema.global_status</code>.
     */
    public final GlobalStatus GLOBAL_STATUS = my.startup.performance_schema.tables.GlobalStatus.GLOBAL_STATUS;

    /**
     * The table <code>performance_schema.global_variables</code>.
     */
    public final GlobalVariables GLOBAL_VARIABLES = my.startup.performance_schema.tables.GlobalVariables.GLOBAL_VARIABLES;

    /**
     * The table <code>performance_schema.persisted_variables</code>.
     */
    public final PersistedVariables PERSISTED_VARIABLES = my.startup.performance_schema.tables.PersistedVariables.PERSISTED_VARIABLES;

    /**
     * The table <code>performance_schema.processlist</code>.
     */
    public final Processlist PROCESSLIST = my.startup.performance_schema.tables.Processlist.PROCESSLIST;

    /**
     * The table <code>performance_schema.session_account_connect_attrs</code>.
     */
    public final SessionAccountConnectAttrs SESSION_ACCOUNT_CONNECT_ATTRS = my.startup.performance_schema.tables.SessionAccountConnectAttrs.SESSION_ACCOUNT_CONNECT_ATTRS;

    /**
     * The table <code>performance_schema.session_status</code>.
     */
    public final SessionStatus SESSION_STATUS = my.startup.performance_schema.tables.SessionStatus.SESSION_STATUS;

    /**
     * The table <code>performance_schema.session_variables</code>.
     */
    public final SessionVariables SESSION_VARIABLES = my.startup.performance_schema.tables.SessionVariables.SESSION_VARIABLES;

    /**
     * The table <code>performance_schema.variables_info</code>.
     */
    public final VariablesInfo VARIABLES_INFO = my.startup.performance_schema.tables.VariablesInfo.VARIABLES_INFO;

    /**
     * No further instances allowed
     */
    private PerformanceSchema() {
        super("performance_schema", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            GlobalStatus.GLOBAL_STATUS,
            GlobalVariables.GLOBAL_VARIABLES,
            PersistedVariables.PERSISTED_VARIABLES,
            Processlist.PROCESSLIST,
            SessionAccountConnectAttrs.SESSION_ACCOUNT_CONNECT_ATTRS,
            SessionStatus.SESSION_STATUS,
            SessionVariables.SESSION_VARIABLES,
            VariablesInfo.VARIABLES_INFO);
    }
}
