/*
 * This file is generated by jOOQ.
 */
package my.startup.performance_schema;


import javax.annotation.processing.Generated;

import my.startup.performance_schema.tables.GlobalStatus;
import my.startup.performance_schema.tables.GlobalVariables;
import my.startup.performance_schema.tables.PersistedVariables;
import my.startup.performance_schema.tables.Processlist;
import my.startup.performance_schema.tables.SessionAccountConnectAttrs;
import my.startup.performance_schema.tables.SessionStatus;
import my.startup.performance_schema.tables.SessionVariables;
import my.startup.performance_schema.tables.VariablesInfo;


/**
 * Convenience access to all tables in performance_schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>performance_schema.global_status</code>.
     */
    public static final GlobalStatus GLOBAL_STATUS = GlobalStatus.GLOBAL_STATUS;

    /**
     * The table <code>performance_schema.global_variables</code>.
     */
    public static final GlobalVariables GLOBAL_VARIABLES = GlobalVariables.GLOBAL_VARIABLES;

    /**
     * The table <code>performance_schema.persisted_variables</code>.
     */
    public static final PersistedVariables PERSISTED_VARIABLES = PersistedVariables.PERSISTED_VARIABLES;

    /**
     * The table <code>performance_schema.processlist</code>.
     */
    public static final Processlist PROCESSLIST = Processlist.PROCESSLIST;

    /**
     * The table <code>performance_schema.session_account_connect_attrs</code>.
     */
    public static final SessionAccountConnectAttrs SESSION_ACCOUNT_CONNECT_ATTRS = SessionAccountConnectAttrs.SESSION_ACCOUNT_CONNECT_ATTRS;

    /**
     * The table <code>performance_schema.session_status</code>.
     */
    public static final SessionStatus SESSION_STATUS = SessionStatus.SESSION_STATUS;

    /**
     * The table <code>performance_schema.session_variables</code>.
     */
    public static final SessionVariables SESSION_VARIABLES = SessionVariables.SESSION_VARIABLES;

    /**
     * The table <code>performance_schema.variables_info</code>.
     */
    public static final VariablesInfo VARIABLES_INFO = VariablesInfo.VARIABLES_INFO;
}
