/*
 * This file is generated by jOOQ.
 */
package my.startup.app;


import javax.annotation.processing.Generated;

import my.startup.app.tables.Contacts;
import my.startup.app.tables.People;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>app</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONTACTS_PRIMARY = Indexes0.CONTACTS_PRIMARY;
    public static final Index PEOPLE_PRIMARY = Indexes0.PEOPLE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONTACTS_PRIMARY = Internal.createIndex("PRIMARY", Contacts.CONTACTS, new OrderField[] { Contacts.CONTACTS.ID }, true);
        public static Index PEOPLE_PRIMARY = Internal.createIndex("PRIMARY", People.PEOPLE, new OrderField[] { People.PEOPLE.ID }, true);
    }
}
