/*
 * This file is generated by jOOQ.
 */
package my.startup.app;


import javax.annotation.processing.Generated;

import my.startup.app.tables.Contacts;
import my.startup.app.tables.People;


/**
 * Convenience access to all tables in app
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>app.Contacts</code>.
     */
    public static final Contacts CONTACTS = Contacts.CONTACTS;

    /**
     * The table <code>app.People</code>.
     */
    public static final People PEOPLE = People.PEOPLE;
}
