/*
 * This file is generated by jOOQ.
 */
package my.startup.app.tables.records;


import javax.annotation.processing.Generated;

import my.startup.app.tables.People;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PeopleRecord extends UpdatableRecordImpl<PeopleRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -1558460102;

    /**
     * Setter for <code>app.People.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>app.People.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>app.People.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>app.People.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>app.People.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>app.People.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return People.PEOPLE.ID;
    }

    @Override
    public Field<String> field2() {
        return People.PEOPLE.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return People.PEOPLE.LAST_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public PeopleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PeopleRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public PeopleRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public PeopleRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PeopleRecord
     */
    public PeopleRecord() {
        super(People.PEOPLE);
    }

    /**
     * Create a detached, initialised PeopleRecord
     */
    public PeopleRecord(Integer id, String firstName, String lastName) {
        super(People.PEOPLE);

        set(0, id);
        set(1, firstName);
        set(2, lastName);
    }
}
