/*
 * This file is generated by jOOQ.
 */
package my.startup.information_schema.tables;


import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import my.startup.information_schema.InformationSchema;
import my.startup.information_schema.enums.EventsIntervalField;
import my.startup.information_schema.tables.records.EventsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Events extends TableImpl<EventsRecord> {

    private static final long serialVersionUID = -1358669862;

    /**
     * The reference instance of <code>information_schema.EVENTS</code>
     */
    public static final Events EVENTS = new Events();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventsRecord> getRecordType() {
        return EventsRecord.class;
    }

    /**
     * The column <code>information_schema.EVENTS.EVENT_CATALOG</code>.
     */
    public final TableField<EventsRecord, String> EVENT_CATALOG = createField(DSL.name("EVENT_CATALOG"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.EVENT_SCHEMA</code>.
     */
    public final TableField<EventsRecord, String> EVENT_SCHEMA = createField(DSL.name("EVENT_SCHEMA"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.EVENT_NAME</code>.
     */
    public final TableField<EventsRecord, String> EVENT_NAME = createField(DSL.name("EVENT_NAME"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.DEFINER</code>.
     */
    public final TableField<EventsRecord, String> DEFINER = createField(DSL.name("DEFINER"), org.jooq.impl.SQLDataType.VARCHAR(288).nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.TIME_ZONE</code>.
     */
    public final TableField<EventsRecord, String> TIME_ZONE = createField(DSL.name("TIME_ZONE"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.EVENT_BODY</code>.
     */
    public final TableField<EventsRecord, String> EVENT_BODY = createField(DSL.name("EVENT_BODY"), org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>information_schema.EVENTS.EVENT_DEFINITION</code>.
     */
    public final TableField<EventsRecord, String> EVENT_DEFINITION = createField(DSL.name("EVENT_DEFINITION"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.EVENT_TYPE</code>.
     */
    public final TableField<EventsRecord, String> EVENT_TYPE = createField(DSL.name("EVENT_TYPE"), org.jooq.impl.SQLDataType.VARCHAR(9).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>information_schema.EVENTS.EXECUTE_AT</code>.
     */
    public final TableField<EventsRecord, Timestamp> EXECUTE_AT = createField(DSL.name("EXECUTE_AT"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>information_schema.EVENTS.INTERVAL_VALUE</code>.
     */
    public final TableField<EventsRecord, String> INTERVAL_VALUE = createField(DSL.name("INTERVAL_VALUE"), org.jooq.impl.SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>information_schema.EVENTS.INTERVAL_FIELD</code>.
     */
    public final TableField<EventsRecord, EventsIntervalField> INTERVAL_FIELD = createField(DSL.name("INTERVAL_FIELD"), org.jooq.impl.SQLDataType.VARCHAR(18).asEnumDataType(my.startup.information_schema.enums.EventsIntervalField.class), this, "");

    /**
     * The column <code>information_schema.EVENTS.SQL_MODE</code>.
     */
    public final TableField<EventsRecord, String> SQL_MODE = createField(DSL.name("SQL_MODE"), org.jooq.impl.SQLDataType.VARCHAR(520).nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.STARTS</code>.
     */
    public final TableField<EventsRecord, Timestamp> STARTS = createField(DSL.name("STARTS"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>information_schema.EVENTS.ENDS</code>.
     */
    public final TableField<EventsRecord, Timestamp> ENDS = createField(DSL.name("ENDS"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>information_schema.EVENTS.STATUS</code>.
     */
    public final TableField<EventsRecord, String> STATUS = createField(DSL.name("STATUS"), org.jooq.impl.SQLDataType.VARCHAR(21).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>information_schema.EVENTS.ON_COMPLETION</code>.
     */
    public final TableField<EventsRecord, String> ON_COMPLETION = createField(DSL.name("ON_COMPLETION"), org.jooq.impl.SQLDataType.VARCHAR(12).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>information_schema.EVENTS.CREATED</code>.
     */
    public final TableField<EventsRecord, Timestamp> CREATED = createField(DSL.name("CREATED"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.LAST_ALTERED</code>.
     */
    public final TableField<EventsRecord, Timestamp> LAST_ALTERED = createField(DSL.name("LAST_ALTERED"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.LAST_EXECUTED</code>.
     */
    public final TableField<EventsRecord, Timestamp> LAST_EXECUTED = createField(DSL.name("LAST_EXECUTED"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>information_schema.EVENTS.EVENT_COMMENT</code>.
     */
    public final TableField<EventsRecord, String> EVENT_COMMENT = createField(DSL.name("EVENT_COMMENT"), org.jooq.impl.SQLDataType.VARCHAR(2048).nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.ORIGINATOR</code>.
     */
    public final TableField<EventsRecord, UInteger> ORIGINATOR = createField(DSL.name("ORIGINATOR"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.CHARACTER_SET_CLIENT</code>.
     */
    public final TableField<EventsRecord, String> CHARACTER_SET_CLIENT = createField(DSL.name("CHARACTER_SET_CLIENT"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.COLLATION_CONNECTION</code>.
     */
    public final TableField<EventsRecord, String> COLLATION_CONNECTION = createField(DSL.name("COLLATION_CONNECTION"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>information_schema.EVENTS.DATABASE_COLLATION</code>.
     */
    public final TableField<EventsRecord, String> DATABASE_COLLATION = createField(DSL.name("DATABASE_COLLATION"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * Create a <code>information_schema.EVENTS</code> table reference
     */
    public Events() {
        this(DSL.name("EVENTS"), null);
    }

    /**
     * Create an aliased <code>information_schema.EVENTS</code> table reference
     */
    public Events(String alias) {
        this(DSL.name(alias), EVENTS);
    }

    /**
     * Create an aliased <code>information_schema.EVENTS</code> table reference
     */
    public Events(Name alias) {
        this(alias, EVENTS);
    }

    private Events(Name alias, Table<EventsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Events(Name alias, Table<EventsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Events(Table<O> child, ForeignKey<O, EventsRecord> key) {
        super(child, key, EVENTS);
    }

    @Override
    public Schema getSchema() {
        return InformationSchema.INFORMATION_SCHEMA;
    }

    @Override
    public Events as(String alias) {
        return new Events(DSL.name(alias), this);
    }

    @Override
    public Events as(Name alias) {
        return new Events(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(String name) {
        return new Events(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(Name name) {
        return new Events(name, null);
    }
}
